#!/usr/bin/env ts-node
/**
 * Generate TypeScript types from ABI files.
 * Usage: npx ts-node src/scripts/generate-types.ts
 */
import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, basename } from 'path';

const ABI_DIR = join(process.cwd(), 'src/contracts/abis');
const OUTPUT_DIR = join(process.cwd(), 'src/types/generated');

function toPascalCase(str: string): string {
  return str
    .replace(/[-_.](.)/g, (_, c: string) => (c as string).toUpperCase())
    .replace(/^(.)/, (_, c: string) => (c as string).toUpperCase());
}

function generateTypeFromABI(contractName: string, abi: unknown[]): string {
  const fnNames = (abi as { type: string; name?: string }[])
    .filter((item) => item.type === 'function' && item.name)
    .map((item) => item.name!);

  const eventNames = (abi as { type: string; name?: string }[])
    .filter((item) => item.type === 'event' && item.name)
    .map((item) => item.name!);

  return `// Auto-generated by generate-types.ts — do not edit manually
// Generated at: ${new Date().toISOString()}

export type ${contractName}FunctionNames = ${fnNames.map((n) => `'${n}'`).join(' | ') || 'never'};
export type ${contractName}EventNames = ${eventNames.map((n) => `'${n}'`).join(' | ') || 'never'};

export interface ${contractName}Contract {
  address: \`0x\${string}\`;
  abi: typeof import('../abis/${contractName}.json');
}
`;
}

async function main() {
  let files: string[];
  try {
    files = readdirSync(ABI_DIR).filter((f) => f.endsWith('.json'));
  } catch {
    console.error(`ABI directory not found: ${ABI_DIR}`);
    process.exit(1);
  }

  // Ensure output dir exists
  try {
    readdirSync(OUTPUT_DIR);
  } catch {
    const { mkdirSync } = await import('fs');
    mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  const indexExports: string[] = [];

  for (const file of files) {
    const contractName = toPascalCase(basename(file, '.json'));
    const abiPath = join(ABI_DIR, file);
    const abi = JSON.parse(readFileSync(abiPath, 'utf-8')) as unknown[];

    const generated = generateTypeFromABI(contractName, abi);
    const outputFile = join(OUTPUT_DIR, `${contractName}.ts`);
    writeFileSync(outputFile, generated);

    indexExports.push(`export type { ${contractName}FunctionNames, ${contractName}EventNames, ${contractName}Contract } from './${contractName}';`);
    console.log(`  ✅ Generated types for ${contractName}`);
  }

  const indexContent = `// Auto-generated index — do not edit manually\n\n${indexExports.join('\n')}\n`;
  writeFileSync(join(OUTPUT_DIR, 'index.ts'), indexContent);

  console.log(`\n✅ Generated types for ${files.length} contract(s) in ${OUTPUT_DIR}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
